config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :totos

  resources :articles

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article), notice: 'Article was successfully updated.'
    end
  end

  def destroy
    @article.destroy
    redirect_to article_path(@article), notice: 'Article was successfully destroyed.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content, data: { editor: 'markdown' }, rows: 10 %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Wikinimous</h1>
<ul>
    <% @articles.each do |article| %>
    <li>
    <%= link_to article.title, article_path(article)%>
    <%= article.content[0...100] %>
  </li>
  <%end%>
</ul>

app/views/articles/show.html.erb
<!-- <h1><%= @article.title %> </h1>
<p><%= @article.content %></p>

 -->

<% content_for(:title) do %>
  Wikinimous - <%= @article.title %>
<% end %>

<article>
  <h1>
    <%= @article.title %>
    <small>
      <%= link_to edit_article_path(@article) do %><i class="fa fa-pencil"></i><% end %>

      <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </small>
  </h1>

  <%= link_to "Back to list", articles_path %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>